### ISSUE TITLE
Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by jasongerbes** [hipstersmoothie/react-glider#1]
The following error occurs when the children of the carousel change:
`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

I believe this is due to the referenced container being modifier by glider.js:
```
// in render() of index.tsx

<div className={this.props.className} ref={this.ref}>
      {this.props.children}
</div>
```

```
// in glider.js

_.track = document.createElement('div')
_.track.className = 'glider-track'
_.ele.appendChild(_.track)
while (_.ele.children.length !== 1) {
    _.track.appendChild(_.ele.children[0])
}
```

React expects the element to have the children specified in the `render()` method, but glider.js has inserted a new `<div>` element and moved the children into it.

When React attempts to update the children, it is unaware of the change made by glider.js and attempts to remove the children it inserted via the `render()` method. This fails as the children have been moved.

It seems to me that the only way to resolve this issue would require a change to glider.js -- Add an option that prevents glider.js from adding the `glider-track` automatically, so that it can be manually added in your `render()` method.

This would look something like:
```
// in render() of index.tsx

<div className={this.props.className} ref={this.ref}>
    <div className="glider-track">
         {this.props.children}
    </div>
</div>
```

```
// in glider.js

if (_.opt.addTrack) {
    _.track = document.createElement('div')
    _.track.className = 'glider-track'
    _.ele.appendChild(_.track)
    while (_.ele.children.length !== 1) {
        _.track.appendChild(_.ele.children[0])
    }
}
else {
    _.track = _ele.children[0]
}
```

**Comment by elkelk** [comment]
For anyone else struggling with this, Glider.js updated the configuration key to `skipTrack`, so add `skipTrack: true` to your options.

**Comment by kevinfarrugia** [comment]
Issue with rehydration will be solved in #119 but is dependent on https://github.com/NickPiscitelli/Glider.js/pull/235

**Comment by kevinfarrugia** [comment]
This is fixed in version 4.x.

**Comment by kevinfarrugia** [comment]
@danielrussellLA I had posted a solution on a related issue: https://github.com/kevinfarrugia/react-glider/issues/121#issuecomment-1271276992

There is also a [demo](https://react-glider.vercel.app/#dynamic_data) with dynamically updated/removed slides.

**Comment by danielrussellLA** [comment]
> @danielrussellLA I had posted a solution on a related issue: [#121 (comment)](https://github.com/kevinfarrugia/react-glider/issues/121#issuecomment-1271276992)
> 
> There is also a [demo](https://react-glider.vercel.app/#dynamic_data) with dynamically updated/removed slides.

thanks @kevinfarrugia !
