### ISSUE TITLE
Glider is not reinitialized after event handlers are updated 

### ISSUE THREAD

**Issue by kevinfarrugia** [hipstersmoothie/react-glider#106]
When an event handler is updated, Glider is not reinitialized with the new event handler.

**Example**
```
    const [activeSlide, setActiveSlide] = React.useState(1);

    const handleSlideChange = (event: CustomEvent) => {
        console.log(activeSlide); // output: 1

        if (event && event.detail) {
            setActiveSlide({activeSlide: event.detail.slide});
        }
    };
```

In the example above, we are updating the state variable `activeSlide` whenever the slide changes, however the value output in the `console.log` will remain 1, even if the value of `activeSlide` has changed.

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v3.0.4`](https://github.com/hipstersmoothie/react-glider/releases/tag/v3.0.4) :rocket:
