### ISSUE TITLE
componentWillUpdate deprecated in React 17

### ISSUE THREAD

**Issue by wingedearth** [hipstersmoothie/react-glider#11]
react-glider is using componentWillUpdate, which is logging warnings to the console in React 16, as it is deemed an unsafe lifecycle method. In React 17 the method will be deprecated unless renamed as UNSAFE_componentWillUpdate (and thus obviously not recommended by React for use).

See: https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate

**Comment by hipstersmoothie** [comment]
Upgraded this component to use hooks! no longer a problem
