### ISSUE TITLE
autoplay support

### ISSUE THREAD

**Issue by dhaval-vira-infoskies** [hipstersmoothie/react-glider#123]
Hello,

I found react-glider working nicely, but there's no option available for autoplay, where sliders play automatically and also some time interval for autoplay.

**Comment by kevinfarrugia** [comment]
Hi @dhaval-vira-infoskies . At the moment there are no plans to support autoplay within `react-glider` as I intend to keep this as lightweight as possible. However it should be possible to implement it from your end using `scrollItem`.

I created a simple demo here:
```
  const callbackRef = React.useCallback((glider) => {
    if (glider) {
      setInterval(() => {
        let index = glider.page;
        if (index < MAX) {
          index += 1;
        } else {
          index = 0;
        }
        glider.scrollItem(index);
      }, INTERVAL);
    }
  }, []);
```

Demo: https://codesandbox.io/s/react-glider-demo-autoplay-bueo14?file=/src/App.js
