### ISSUE TITLE
`glider-dots` class is repeated multiple times on the same element

### ISSUE THREAD

**Issue by kevinfarrugia** [hipstersmoothie/react-glider#31]
The class name `glider-dots` is assigned to the same class multiple times instead of one time. This could be replicated in the storybook demo (all examples) by inspecting the HTML of the element with `id="dots"`.

**Effects**
This does not cause any visible issues but is semantically incorrect and bloats the HTML.

**Priority**
Low

**Workaround**
N/A

**Comment by hipstersmoothie** [comment]
PRs welcome! I don't really use this project myself so any contribution is welcome ❤️
