### ISSUE TITLE
Storybook URL returns 404

### ISSUE THREAD

**Issue by kevinfarrugia** [hipstersmoothie/react-glider#32]
The storybook URL (http://hipstersmoothie.com/react-glider/?selectedKind=Glider&selectedStory=Playground&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) linked in the project returns a 404.

The `gh-pages` branch contains a working storybook and the linked URL may be changed to the working https://hipstersmoothie.github.io/react-glider

**Comment by kevinfarrugia** [comment]
@hipstersmoothie I am unable to update this myself as it isn't a code change. Could you kindly see to it please?

**Comment by hipstersmoothie** [comment]
I think i've fixed this
