### ISSUE TITLE
Allow 'Element' type for arrows

### ISSUE THREAD

**Issue by kdembler** [hipstersmoothie/react-glider#36]
First off, thanks for the library!

Currently, the arrows prop allows object with keys `prev` and `next` which both must be `string`. However, per the Glider.js documentation, element instances can be passed here as well instead of the selectors. See https://nickpiscitelli.github.io/Glider.js/ -> Settings -> arrows

It'd be great if this library took that into account as well

**Comment by yashvesikar** [comment]
I messed around with this issue here: https://github.com/yashvesikar/react-glider/commit/fc742b3af6327144cba2568510d8734a9d4e464d does this seem like an acceptable solution to the problem? 

Thanks for any input :) I can make a PR if it looks good. @kevinfarrugia

**Comment by kevinfarrugia** [comment]
Left a comment on the PR. Awaiting your feedback.

**Comment by mkampmey** [comment]
@yashvesikar @kevinfarrugia Can we merge the PR? This issue also has the effect that react-glider is not correctly working when you use it within web components.

**Comment by kevinfarrugia** [comment]
@mkampmey do you have a demo using Web Components so that I may include it in the test suite?

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v3.0.0`](https://github.com/hipstersmoothie/react-glider/releases/tag/v3.0.0) :rocket:
