### ISSUE TITLE
Bundle size question

### ISSUE THREAD

**Issue by cameronbraid** [hipstersmoothie/react-glider#50]
Hi,

The bundlesize jumped a bit with the latest release
 v2.0.4 is  **3.4kB** (https://bundlephobia.com/result?p=react-glider@2.0.4)
 v2.1.0 is  **6.3kB** (https://bundlephobia.com/result?p=react-glider@2.1.0)

Are these bundlephobia sizes appropriate ?

It shows that  `@reach/utils` is included, however does it get tree-shaked ?

Seems like the increase came from `@reach/auto-id` however bundlesize shows its only **436B**

**Comment by kevinfarrugia** [comment]
Version 2.0.4 didn't include `react` as a dependency.
