### ISSUE TITLE
Showing `undefined` class on glider-slider on storybook example

### ISSUE THREAD

**Issue by kevinfarrugia** [hipstersmoothie/react-glider#62]
_This only affects Storybook, however I would like to resolve it to have a better reference for users._

When a user does not specify a `className` on Storybook, then the slides have `undefined` as a class. 

```
<div class="glider-slide **undefined** active center visible" data-gslide="0" style="height: auto; width: 1238px;"><h1>1</h1></div>
```

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v2.2.0`](https://github.com/hipstersmoothie/react-glider/releases/tag/v2.2.0) :rocket:
