### ISSUE TITLE
Type definitions for events are incorrect

### ISSUE THREAD

**Issue by kevinfarrugia** [hipstersmoothie/react-glider#63]
The type definitions for the events are not correct as there is only a single parameter being passed, the `Event`. The `Context` is not in use.

**Example:**
```
onSlideVisible?(context: any, event: Event): void;
```
Should become
```
onSlideVisible?(event: Event): void;
```

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v2.2.0`](https://github.com/hipstersmoothie/react-glider/releases/tag/v2.2.0) :rocket:
