### ISSUE TITLE
`glider-slide-visible` and `glider-slide-hidden` events only fire with `scrollLock`

### ISSUE THREAD

**Issue by kevinfarrugia** [hipstersmoothie/react-glider#66]
glider-js exposes two events, `glider-slide-visible` and `glider-slide-hidden` which fire when a slide is visible or hidden respectively. On the glider-js package, these fire in all the following three cases:
- Horizontal scrolling (touch or mouse)
- Horizontal scrolling (touch or mouse) with `scrollLock: true`
- Clicking on the dots

On the react-glider project, the first scenario does not fire any events.
⚠ Horizontal scrolling (touch or mouse)
✅ Horizontal scrolling (touch or mouse) with `scrollLock: true`
✅ Clicking on the dots

**Comment by hipstersmoothie** [comment]
Have your other PRs fixed this?

**Comment by kevinfarrugia** [comment]
No not yet. I was going to look into it separately.

**Comment by kevinfarrugia** [comment]
I investigated this and the root cause is on `glider-js` as it previously used to use `_.scrollLeft` and this should be `_.ele.scrollLeft`. This is fixed on `glider-js: 1.7.7` so I have upgraded the package.json dependency to that version.

For more info on the bug on `glider-js`:
- Introduced here: https://github.com/NickPiscitelli/Glider.js/pull/146
- Reverted here: https://github.com/NickPiscitelli/Glider.js/commit/18ff90b38f22fc84a2f22fb115244a1a7f7e663b#diff-f4b8488a4d72712239240832f06f48a1aaf0e2ec4775c8f877a14e4e11f3d39e

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v2.2.1`](https://github.com/hipstersmoothie/react-glider/releases/tag/v2.2.1) :rocket:
