### ISSUE TITLE
Cannot navigate to another page with anchor tag

### ISSUE THREAD

**Issue by LouisKwong** [hipstersmoothie/react-glider#70]
Hi,

I am using react-glider in my project. I put anchor tag in Glider tag.
 i.e. 
`<Glider><a href="https://example.com" target="_blank">Example</a></Glider>`
However, I cannot navigate to the web page. Is there any way to achieve page navigation using react-glider for each slide?

Thanks.

**Comment by kevinfarrugia** [comment]
@LouisKwong can you please include a minimal reproducible example as I am unable to - you may want to create a fork and add a story to storybook. It should work as expected. Example:

```
    <Glider>
      <a href="https://example1.com" target="_blank">
        1
      </a>
      <a href="https://example2.com" target="_blank">
        2
      </a>
      <a href="https://example3.com" target="_blank">
        3
      </a>
    </Glider>
```

**Comment by kevinfarrugia** [comment]
Closed due to inactivity.
