### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by lourensdev** [hipstersmoothie/react-glider#72]
How are you supposed to add options with this wrapper? There is no explanation in the readme, and you can't follow the original documentation because the implementation is not the same.

**Comment by robindrost** [comment]
There is a storybook available in the code with some options you can set :).

https://github.com/hipstersmoothie/react-glider/blob/master/stories/index.tsx

Maybe based on this you are able to update the documentation for others.

**Comment by lourensdev** [comment]
@robindrost I hear you, unfortunately, that assumes the developer to have prior knowledge of Storybook. I eventually managed to sort it myself but should really be in the documentation/readme

**Comment by kevinfarrugia** [comment]
I created a PR with some documentation. Please feel free to review and leave your feedback.

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v2.2.1`](https://github.com/hipstersmoothie/react-glider/releases/tag/v2.2.1) :rocket:
