### ISSUE TITLE
Autoplay?

### ISSUE THREAD

**Issue by paulsheldrake** [hipstersmoothie/react-glider#84]
Hello

It looks like autoplay isn't a feature in the react component. Is that by design?

**Comment by kevinfarrugia** [comment]
Correct. react-glider is a react wrapper for [Glider.js](https://nickpiscitelli.github.io/Glider.js/).

> Glider.js is not a drop-in replacement for carousels. It lacks a lot of functionality provided by Slick.js or other featured carousels. An non-exhaustive list would consist of things like infinite looping, autoplay, variable width, vertical support, custom transitions, etc.
