### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by chrisgbaker** [hipstersmoothie/react-glider#87]
# Overview
Hello! I was curious if React 17 support was on the roadmap to be added to `react-glider`? It appears this `warning` is not a direct issue with this package, but some dependencies of this package, specifically `@reach/auto-id`, which has been updated to signify support for React 17.

Thanks!

## Package versions
react-glider version: @latest

**Comment by kevinfarrugia** [comment]
There is an open PR #83. Can you please check if it works well for you?

**Comment by kevinfarrugia** [comment]
Tested on React 17. Demo link on [Code Sandbox](https://codesandbox.io/s/react-glider-demo-y5klj)
