### ISSUE TITLE
Multiple Gliders on same page, the arrows won't work

### ISSUE THREAD

**Issue by sohailhaider** [hipstersmoothie/react-glider#88]
If we have multiple gliders on same page, the arrows work for first glider but not for the second.

**Comment by sohailhaider** [comment]
UPDATE: by looking into source found out, for more than 1 gliders on same page. arrows need to have different ids to work. I guess we should document it, I can se we have a example with same scenario but doesn't say that explicitly we need to have new arrows.

**Comment by kevinfarrugia** [comment]
Updated documentation in #86
