### ISSUE TITLE
Glider events not firing up

### ISSUE THREAD

**Issue by yaronA** [hipstersmoothie/react-glider#9]
I tried to register to events but none of them are being fired:

      <Glider
        slidesToScroll={5}
        slidesToShow={5}
        draggable={true}
        onRefresh={() => handleOnLoad}
        onLoad={() => handleOnLoad}
        onSlideVisible={() => handleOnLoad}
      >

  function handleOnLoad(context: any, event: Event) {
  }

from documentation:
     /** Called after Glider.js is first initialized */
    onLoad?(context: any, event: Event): void;
    /** Called whenever a slide a shown. Passed an object containing the slide index */
    onSlideVisible?(context: any, event: Event): void;
    /** Called whenever Glider.js refreshes it's elements or settings */
    onRefresh?(context: any, event: Event): void;

**Comment by hipstersmoothie** [comment]
@yaronA If you make a PR with a fix I will merge and release quickly!
